# The name of your Worker. This will be part of its URL (saturday.mqrbxn.dev).
name = "saturday"

# The entry point for your Worker's code.
main = "src/index.ts"

# Specifies compatibility with a recent version of the Workers runtime.
compatibility_date = "2024-07-18"

# This crucial part links your code to the Cloudflare AI service.
# In the dashboard, this is done in Settings > Variables > AI Bindings.
[[ai]]
binding = "AI"
